### ISSUE TITLE
Problem with update

### ISSUE THREAD

**Issue by lumiror** [syssi/esphome-ant-bms#67]
Hello, I wanted to update the compilation after installing the new homassistant version, but it is not possible because I have this error. Can you please advise how to fix it. Thank you

![image](https://user-images.githubusercontent.com/33359116/235489257-2b65c56f-ed8d-4e1f-bb54-4bf71cfaf86b.png)

**Comment by syssi** [comment]
Please rename `uart0` to `uart_0`. This should solve the validation issue.

**Comment by lumiror** [comment]
I tried that, but it didn't work

![image](https://user-images.githubusercontent.com/33359116/235531679-dd48bc3d-ace2-4eee-817e-935a206560f0.png)

**Comment by syssi** [comment]
Please remove the `ant_modbus` section and update the `ant_bms` section to:

```
uart:
  - id: uart_0
    baud_rate: 19200
    rx_buffer_size: 384
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}

ant_bms:
  - id: bms0
    uart_id: uart_0
    update_interval: 5s
    rx_timeout: ${rx_timeout}
    supports_new_commands: false
```

**Comment by lumiror** [comment]
something is still wrong, please take a look

![image](https://user-images.githubusercontent.com/33359116/235731728-00e52fea-3d00-4007-b9b2-e5120e941150.png)

**Comment by syssi** [comment]
Please remove line 54 (`rx_timeout: ...`) and try again.

**Comment by lumiror** [comment]
and line 55 should be true or false because before it was true and now it is false?

**Comment by lumiror** [comment]
and again, please, in the new version after 2021, it's like this, what should I delete there.

![image](https://user-images.githubusercontent.com/33359116/235736357-8268d730-9534-4437-940c-365de62445db.png)

**Comment by lumiror** [comment]
can it be like this
![image](https://user-images.githubusercontent.com/33359116/235737213-c5307bc4-620d-4a19-ba34-37cd3b45e568.png)

**Comment by syssi** [comment]
It's pretty the same here but `supports_new_commands: true`:

```
uart:
  - id: uart_0
    baud_rate: 19200
    rx_buffer_size: 384
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}

ant_bms:
  - id: bms0
    uart_id: uart_0
    update_interval: 5s
    password: "${password}"
    supports_new_commands: true
```

**Comment by lumiror** [comment]
so I understood it correctly.
but why is it true in one and false in the other?

**Comment by syssi** [comment]
Probably because of the different hardware/software version of the BMS?
